import json
from datetime import datetime, timezone
from pathlib import Path

from character_graph.storage import load_graph
import local_chatbot.lore_import as lore_import
from local_chatbot.lore_import import (
    BACKUP_KIND_BACKUP,
    BACKUP_KIND_SNAPSHOT,
    backup_lore_files,
    clear_local_lore,
    import_lore_directory,
    list_lore_backups,
    read_lore_backup_date,
    read_backup_date,
    read_backup_kind,
    read_backup_snapshot_date,
    restore_lore_backup,
)


ROOT_DIR = Path(__file__).resolve().parents[1]
FIXTURES_DIR = ROOT_DIR / "tests" / "fixtures"


def minimal_graph_json(name: str, source_file: str) -> str:
    node_id = name.lower().replace(" ", "_")
    return json.dumps(
        {
            "schema_version": "0.3.0",
            "primary_character": {
                "id": node_id,
                "name": name,
                "source_file": source_file,
            },
            "characters": {
                node_id: {
                    "name": name,
                    "role": "primary character",
                    "summary": "",
                    "source_spans": [],
                }
            },
            "attributes": {},
            "places": {},
            "relationships": [],
            "evidence": [],
            "embeddings": {},
        },
        indent=2,
    )


def test_import_lore_directory_copies_fixture_subdirectories(tmp_path, monkeypatch):
    characters_dir = tmp_path / "docs" / "lore" / "character_sheets"
    places_dir = tmp_path / "docs" / "lore" / "places"
    session_notes_dir = tmp_path / "docs" / "lore" / "session_notes"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    monkeypatch.setattr(lore_import, "CHARACTERS_DIR", characters_dir)
    monkeypatch.setattr(lore_import, "PLACES_DIR", places_dir)
    monkeypatch.setattr(lore_import, "SESSION_NOTES_DIR", session_notes_dir)
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "ensure_base_dirs", lambda: None)

    summary = import_lore_directory(FIXTURES_DIR)

    assert summary.characters == 3
    assert summary.places == 1
    assert summary.session_notes == 2
    assert (characters_dir / "Jory_Ravenmark.md").exists()
    assert "- Autogenerated by generate_random_characters.py" in (
        characters_dir / "Orin_Nightbloom.md"
    ).read_text(encoding="utf-8")
    assert (places_dir / "Atlantia_Lore.md").exists()
    assert (session_notes_dir / "Family_Tree.md").exists()
    assert (session_notes_dir / "Session_Notes_Fixture.md").exists()


def test_import_lore_directory_converts_old_txt_session_notes_to_markdown(tmp_path, monkeypatch):
    source_dir = tmp_path / "import"
    source_notes_dir = source_dir / "session_notes"
    source_notes_dir.mkdir(parents=True)
    (source_notes_dir / "Session_Notes.txt").write_text("Vivit met Jory near Atlantia.\n", encoding="utf-8")
    session_notes_dir = tmp_path / "world_building" / "lore" / "session_notes"
    monkeypatch.setattr(lore_import, "CHARACTERS_DIR", tmp_path / "world_building" / "lore" / "character_sheets")
    monkeypatch.setattr(lore_import, "PLACES_DIR", tmp_path / "world_building" / "lore" / "places")
    monkeypatch.setattr(lore_import, "SESSION_NOTES_DIR", session_notes_dir)
    monkeypatch.setattr(lore_import, "META_DATA_DIR", tmp_path / "world_building" / "meta_data")
    monkeypatch.setattr(lore_import, "ensure_base_dirs", lambda: None)

    summary = import_lore_directory(source_dir)

    assert summary.session_notes == 1
    assert not (session_notes_dir / "Session_Notes.txt").exists()
    assert (session_notes_dir / "Session_Notes.md").read_text(encoding="utf-8") == "Vivit met Jory near Atlantia.\n"


def test_import_lore_directory_can_skip_existing_files(tmp_path, monkeypatch):
    places_dir = tmp_path / "docs" / "lore" / "places"
    places_dir.mkdir(parents=True)
    existing = places_dir / "Atlantia_Lore.md"
    existing.write_text("# Existing Atlantia\n", encoding="utf-8")
    monkeypatch.setattr(lore_import, "CHARACTERS_DIR", tmp_path / "docs" / "lore" / "character_sheets")
    monkeypatch.setattr(lore_import, "PLACES_DIR", places_dir)
    monkeypatch.setattr(lore_import, "SESSION_NOTES_DIR", tmp_path / "docs" / "lore" / "session_notes")
    monkeypatch.setattr(lore_import, "META_DATA_DIR", tmp_path / "world_building" / "meta_data")
    monkeypatch.setattr(lore_import, "ensure_base_dirs", lambda: None)

    summary = import_lore_directory(FIXTURES_DIR, overwrite=False)

    assert summary.places == 0
    assert existing.read_text(encoding="utf-8") == "# Existing Atlantia\n"


def test_clear_local_lore_cleans_configured_lore_dir(tmp_path, monkeypatch):
    lore_dir = tmp_path / "data" / "lore"
    character_metadata_dir = tmp_path / "data" / "character_metadata"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    characters_dir = lore_dir / "character_sheets"
    places_dir = lore_dir / "places"
    session_notes_dir = lore_dir / "session_notes"
    generated_character_dir = character_metadata_dir / "Draft"
    stale_profile = generated_character_dir / "PROFILE.json"
    stale_memory = generated_character_dir / "MEMORY.md"
    stale_graph = meta_data_dir / "character_graph" / "Jory_Ravenmark.graph.json"
    monkeypatch.setattr(lore_import, "CHARACTERS_DIR", characters_dir)
    monkeypatch.setattr(lore_import, "LORE_DIR", lore_dir)
    monkeypatch.setattr(lore_import, "GENERATED_LORE_DIR", lore_dir)
    monkeypatch.setattr(lore_import, "CHARACTER_METADATA_DIR", character_metadata_dir)
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "PLACES_DIR", places_dir)
    monkeypatch.setattr(lore_import, "SESSION_NOTES_DIR", session_notes_dir)
    monkeypatch.setattr(
        lore_import,
        "ensure_base_dirs",
        lambda: [
            path.mkdir(parents=True, exist_ok=True)
            for path in (characters_dir, places_dir, session_notes_dir, lore_dir, character_metadata_dir, meta_data_dir)
        ],
    )

    import_lore_directory(FIXTURES_DIR)
    generated_character_dir.mkdir(parents=True)
    stale_graph.parent.mkdir(parents=True)
    stale_profile.write_text("{}", encoding="utf-8")
    stale_memory.write_text("Draft memory.", encoding="utf-8")
    stale_graph.write_text("{}", encoding="utf-8")

    summary = clear_local_lore()

    assert summary.characters == 3
    assert summary.places == 1
    assert summary.session_notes == 2
    assert summary.metadata == 1
    assert not (characters_dir / "Jory_Ravenmark.md").exists()
    assert not (places_dir / "Atlantia_Lore.md").exists()
    assert not (session_notes_dir / "Family_Tree.md").exists()
    assert not stale_profile.exists()
    assert not stale_memory.exists()
    assert not stale_graph.exists()
    assert characters_dir.exists()
    assert places_dir.exists()
    assert session_notes_dir.exists()
    assert lore_dir.exists()
    assert character_metadata_dir.exists()
    assert meta_data_dir.exists()


def test_backup_lore_files_copies_current_lore_and_records_date(tmp_path, monkeypatch):
    lore_dir = tmp_path / "world_building" / "lore"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    backup_dir = tmp_path / "world_building" / "backup"
    character_file = lore_dir / "character_sheets" / "Jory_Ravenmark.md"
    place_file = lore_dir / "places" / "Atlantia_Lore.md"
    graph_file = meta_data_dir / "character_graph" / "Jory_Ravenmark.graph.json"
    character_file.parent.mkdir(parents=True)
    place_file.parent.mkdir(parents=True)
    graph_file.parent.mkdir(parents=True)
    character_file.write_text("# Jory Ravenmark\n", encoding="utf-8")
    place_file.write_text("# Atlantia\n", encoding="utf-8")
    graph_file.write_text(minimal_graph_json("Jory Ravenmark", "Jory_Ravenmark.md"), encoding="utf-8")
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "ensure_base_dirs", lambda: None)
    timestamp = datetime(2026, 7, 13, 9, 30, tzinfo=timezone.utc)

    summary = backup_lore_files(lore_dir, backup_dir, backup_date=timestamp)

    assert summary.files == 3
    assert summary.backup_dir == backup_dir.resolve()
    assert summary.backup_date == timestamp
    assert (
        backup_dir / "character_sheets" / "Jory_Ravenmark.md"
    ).read_text(encoding="utf-8") == "# Jory Ravenmark\n"
    assert (backup_dir / "places" / "Atlantia_Lore.md").read_text(encoding="utf-8") == "# Atlantia\n"
    copied_graph = load_graph(backup_dir / "meta_data" / "character_graph" / "Jory_Ravenmark.graph.json")
    assert copied_graph is not None
    assert copied_graph.primary_character.name == "Jory Ravenmark"
    assert read_lore_backup_date(backup_dir) == timestamp


def test_import_lore_directory_restores_metadata_from_backup(tmp_path, monkeypatch):
    backup_dir = tmp_path / "world_building" / "backup"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    graph_file = backup_dir / "meta_data" / "character_graph" / "Jory_Ravenmark.graph.json"
    graph_file.parent.mkdir(parents=True)
    graph_file.write_text(minimal_graph_json("Jory Ravenmark", "Jory_Ravenmark.md"), encoding="utf-8")
    monkeypatch.setattr(lore_import, "CHARACTERS_DIR", tmp_path / "world_building" / "lore" / "character_sheets")
    monkeypatch.setattr(lore_import, "PLACES_DIR", tmp_path / "world_building" / "lore" / "places")
    monkeypatch.setattr(lore_import, "SESSION_NOTES_DIR", tmp_path / "world_building" / "lore" / "session_notes")
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "ensure_base_dirs", lambda: None)

    summary = import_lore_directory(backup_dir)

    assert summary.metadata == 1
    restored_graph = load_graph(meta_data_dir / "character_graph" / "Jory_Ravenmark.graph.json")
    assert restored_graph is not None
    assert restored_graph.primary_character.name == "Jory Ravenmark"


def test_restore_lore_backup_deletes_lore_missing_from_backup(tmp_path, monkeypatch):
    backup_dir = tmp_path / "world_building" / "backup"
    current_backup_dir = tmp_path / "world_building" / "current_backup"
    lore_dir = tmp_path / "world_building" / "lore"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    characters_dir = lore_dir / "character_sheets"
    places_dir = lore_dir / "places"
    session_notes_dir = lore_dir / "session_notes"
    stale_place = places_dir / "Stale_Place.md"
    backup_character = backup_dir / "character_sheets" / "Jory_Ravenmark.md"
    stale_place.parent.mkdir(parents=True)
    backup_character.parent.mkdir(parents=True)
    stale_place.write_text("# Stale Place\n", encoding="utf-8")
    backup_character.write_text("# Jory Ravenmark\n", encoding="utf-8")
    backup_source_snapshot_date = datetime(2026, 7, 12, 9, 30, tzinfo=timezone.utc)
    backup_lore_files(
        backup_dir,
        backup_dir,
        backup_date=backup_source_snapshot_date,
        snapshot_date=backup_source_snapshot_date,
    )
    timestamps = iter(
        [
            datetime(2026, 7, 18, 15, 41, tzinfo=timezone.utc),
            datetime(2026, 7, 18, 15, 42, tzinfo=timezone.utc),
        ]
    )
    monkeypatch.setattr(lore_import, "LORE_DIR", lore_dir)
    monkeypatch.setattr(lore_import, "GENERATED_LORE_DIR", lore_dir)
    monkeypatch.setattr(lore_import, "CHARACTER_METADATA_DIR", tmp_path / "data" / "character_metadata")
    monkeypatch.setattr(lore_import, "CHARACTERS_DIR", characters_dir)
    monkeypatch.setattr(lore_import, "PLACES_DIR", places_dir)
    monkeypatch.setattr(lore_import, "SESSION_NOTES_DIR", session_notes_dir)
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "WORLD_BUILDING_BACKUP_DIR", current_backup_dir)
    monkeypatch.setattr(lore_import, "current_backup_timestamp", lambda: next(timestamps))
    monkeypatch.setattr(
        lore_import,
        "ensure_base_dirs",
        lambda: [
            path.mkdir(parents=True, exist_ok=True)
            for path in (characters_dir, places_dir, session_notes_dir, lore_dir, meta_data_dir)
        ],
    )

    summary = restore_lore_backup(backup_dir)

    assert summary.characters == 1
    assert (characters_dir / "Jory_Ravenmark.md").exists()
    assert not stale_place.exists()
    backups = list_lore_backups(current_backup_dir)
    assert backups[0].label.startswith("Restored ")
    assert backups[1].label.startswith("Snapshot ")
    assert backups[0].snapshot_date == backup_source_snapshot_date
    assert backups[0].backup_date == datetime(2026, 7, 18, 15, 42, tzinfo=timezone.utc)
    assert backups[1].snapshot_date == datetime(2026, 7, 18, 15, 41, tzinfo=timezone.utc)
    assert backups[1].backup_date == datetime(2026, 7, 18, 15, 41, tzinfo=timezone.utc)
    assert (backups[0].path / "character_sheets" / "Jory_Ravenmark.md").exists()
    assert (backups[1].path / "places" / "Stale_Place.md").exists()


def test_backup_lore_files_updates_existing_backup_without_deleting_missing_files(tmp_path, monkeypatch):
    lore_dir = tmp_path / "world_building" / "lore"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    backup_dir = tmp_path / "world_building" / "backup"
    old_backup_file = backup_dir / "session_notes" / "Old_Note.md"
    current_note = lore_dir / "session_notes" / "Current_Note.md"
    old_backup_file.parent.mkdir(parents=True)
    current_note.parent.mkdir(parents=True)
    old_backup_file.write_text("# Old Note\n", encoding="utf-8")
    current_note.write_text("# Current Note\n", encoding="utf-8")
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "ensure_base_dirs", lambda: None)

    summary = backup_lore_files(lore_dir, backup_dir)

    assert summary.files == 1
    assert old_backup_file.exists()
    assert (backup_dir / "session_notes" / "Current_Note.md").exists()


def test_backup_lore_files_can_create_selectable_snapshot(tmp_path, monkeypatch):
    lore_dir = tmp_path / "world_building" / "lore"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    backup_dir = tmp_path / "world_building" / "backup"
    character_file = lore_dir / "character_sheets" / "Jory_Ravenmark.md"
    character_file.parent.mkdir(parents=True)
    character_file.write_text("# Jory Ravenmark\n", encoding="utf-8")
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "ensure_base_dirs", lambda: None)
    timestamp = datetime(2026, 7, 13, 9, 30, tzinfo=timezone.utc)

    summary = backup_lore_files(
        lore_dir,
        backup_dir,
        backup_date=timestamp,
        snapshot=True,
        backup_kind=BACKUP_KIND_SNAPSHOT,
    )
    backups = list_lore_backups(backup_dir)

    assert summary.backup_dir == backup_dir / "2026-07-13_09-30-00"
    assert (summary.backup_dir / "character_sheets" / "Jory_Ravenmark.md").exists()
    assert backups[0].path == summary.backup_dir
    assert backups[0].label.startswith("Snapshot 2026-07-13")
    assert read_backup_kind(summary.backup_dir) == BACKUP_KIND_SNAPSHOT


def test_auto_backup_uses_backup_label(tmp_path, monkeypatch):
    lore_dir = tmp_path / "world_building" / "lore"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    backup_dir = tmp_path / "world_building" / "backup"
    character_file = lore_dir / "character_sheets" / "Jory_Ravenmark.md"
    character_file.parent.mkdir(parents=True)
    character_file.write_text("# Jory Ravenmark\n", encoding="utf-8")
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "ensure_base_dirs", lambda: None)
    timestamp = datetime(2026, 7, 13, 9, 30, tzinfo=timezone.utc)

    backup_lore_files(lore_dir, backup_dir, backup_date=timestamp)
    backups = list_lore_backups(backup_dir)

    assert backups[0].label.startswith("Backup - 2026-07-13")
    assert read_backup_kind(backup_dir) == BACKUP_KIND_BACKUP
    assert read_backup_snapshot_date(backup_dir) == timestamp
    assert read_backup_date(backup_dir) == timestamp


def test_restored_backup_uses_snapshot_date_label_and_backup_date_sort(tmp_path, monkeypatch):
    lore_dir = tmp_path / "world_building" / "lore"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    backup_dir = tmp_path / "world_building" / "backup"
    character_file = lore_dir / "character_sheets" / "Jory_Ravenmark.md"
    character_file.parent.mkdir(parents=True)
    character_file.write_text("# Jory Ravenmark\n", encoding="utf-8")
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "ensure_base_dirs", lambda: None)
    restored_snapshot_date = datetime(2026, 7, 12, 9, 30, tzinfo=timezone.utc)
    restored_backup_date = datetime(2026, 7, 13, 10, 30, tzinfo=timezone.utc)
    later_snapshot_date = datetime(2026, 7, 13, 9, 30, tzinfo=timezone.utc)

    restored = backup_lore_files(
        lore_dir,
        backup_dir,
        backup_date=restored_backup_date,
        snapshot_date=restored_snapshot_date,
        snapshot=True,
        backup_kind=lore_import.BACKUP_KIND_RESTORED,
    )
    later_snapshot = backup_lore_files(
        lore_dir,
        backup_dir,
        backup_date=later_snapshot_date,
        snapshot_date=later_snapshot_date,
        snapshot=True,
        backup_kind=BACKUP_KIND_SNAPSHOT,
    )
    backups = list_lore_backups(backup_dir)

    assert backups[0].path == restored.backup_dir
    assert backups[0].label.startswith("Restored 2026-07-12")
    assert backups[0].backup_date == restored_backup_date
    assert backups[0].snapshot_date == restored_snapshot_date
    assert read_backup_snapshot_date(restored.backup_dir) == restored_snapshot_date
    assert read_backup_date(restored.backup_dir) == restored_backup_date
    metadata = json.loads((restored.backup_dir / lore_import.LORE_BACKUP_METADATA).read_text(encoding="utf-8"))
    assert metadata["snapshot_date"] == restored_snapshot_date.isoformat(timespec="seconds")
    assert metadata["backup_date"] == restored_backup_date.isoformat(timespec="seconds")
    assert "snapshot_creation_date" not in metadata
    assert "created_at" not in metadata
    assert "updated_at" not in metadata
    assert backups[1].path == later_snapshot.backup_dir


def test_restore_dropdown_keeps_auto_backup_below_new_restore_snapshots(tmp_path, monkeypatch):
    source_backup_dir = tmp_path / "source_backup"
    current_backup_dir = tmp_path / "world_building" / "backup"
    lore_dir = tmp_path / "world_building" / "lore"
    meta_data_dir = tmp_path / "world_building" / "meta_data"
    characters_dir = lore_dir / "character_sheets"
    places_dir = lore_dir / "places"
    session_notes_dir = lore_dir / "session_notes"
    current_character = characters_dir / "Current.md"
    source_character = source_backup_dir / "character_sheets" / "Restored.md"
    current_character.parent.mkdir(parents=True)
    source_character.parent.mkdir(parents=True)
    current_character.write_text("# Current\n", encoding="utf-8")
    source_character.write_text("# Restored\n", encoding="utf-8")
    auto_backup_date = datetime(2026, 7, 18, 15, 40, tzinfo=timezone.utc)
    source_snapshot_date = datetime(2026, 7, 15, 15, 42, tzinfo=timezone.utc)
    backup_lore_files(
        lore_dir,
        current_backup_dir,
        backup_date=auto_backup_date,
        snapshot_date=auto_backup_date,
    )
    backup_lore_files(
        source_backup_dir,
        source_backup_dir,
        backup_date=source_snapshot_date,
        snapshot_date=source_snapshot_date,
    )
    timestamps = iter(
        [
            datetime(2026, 7, 18, 15, 41, tzinfo=timezone.utc),
            datetime(2026, 7, 18, 15, 42, tzinfo=timezone.utc),
        ]
    )
    monkeypatch.setattr(lore_import, "LORE_DIR", lore_dir)
    monkeypatch.setattr(lore_import, "GENERATED_LORE_DIR", lore_dir)
    monkeypatch.setattr(lore_import, "CHARACTER_METADATA_DIR", tmp_path / "data" / "character_metadata")
    monkeypatch.setattr(lore_import, "CHARACTERS_DIR", characters_dir)
    monkeypatch.setattr(lore_import, "PLACES_DIR", places_dir)
    monkeypatch.setattr(lore_import, "SESSION_NOTES_DIR", session_notes_dir)
    monkeypatch.setattr(lore_import, "META_DATA_DIR", meta_data_dir)
    monkeypatch.setattr(lore_import, "WORLD_BUILDING_BACKUP_DIR", current_backup_dir)
    monkeypatch.setattr(lore_import, "current_backup_timestamp", lambda: next(timestamps))
    monkeypatch.setattr(
        lore_import,
        "ensure_base_dirs",
        lambda: [
            path.mkdir(parents=True, exist_ok=True)
            for path in (characters_dir, places_dir, session_notes_dir, lore_dir, meta_data_dir)
        ],
    )

    restore_lore_backup(source_backup_dir)
    backups = list_lore_backups(current_backup_dir)

    assert [backup.kind for backup in backups[:3]] == [
        lore_import.BACKUP_KIND_RESTORED,
        BACKUP_KIND_SNAPSHOT,
        BACKUP_KIND_BACKUP,
    ]
    assert backups[0].label == lore_import.format_backup_option_label(
        lore_import.BACKUP_KIND_RESTORED,
        source_snapshot_date,
    )
    assert backups[0].backup_date == datetime(2026, 7, 18, 15, 42, tzinfo=timezone.utc)
    assert backups[1].label == lore_import.format_backup_option_label(
        BACKUP_KIND_SNAPSHOT,
        datetime(2026, 7, 18, 15, 41, tzinfo=timezone.utc),
    )
    assert backups[1].backup_date == datetime(2026, 7, 18, 15, 41, tzinfo=timezone.utc)
    assert backups[2].label == lore_import.format_backup_option_label(
        BACKUP_KIND_BACKUP,
        auto_backup_date,
    )
